# config/routes.yaml
api_users:
    path: /api/users
    controller: App\Controller\UserController::create
    methods: ['POST']

app_security:
    path: /security
    controller: App\Controller\SecurityController::security
    methods: ['GET']

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: ['POST']

api_update_user:
    path: /api/users/{id}
    controller: App\Controller\UserController::update
    methods: ['POST']

api_get_user_by_id:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUserById
    methods: ['GET']

