# config/routes.yaml
api_users:
    path: /api/users
    controller: App\Controller\UserController::create
    methods: ['POST']
    options:
        swagger:
            summary: Creates a new user
            description: Creates a new user
            responses:
                201: { description: 'User created' }
                400: { description: 'Invalid request' }
                409: { description: 'User already exists' }

app_security:
    path: /security
    controller: App\Controller\SecurityController::security
    methods: ['GET']
    options:
        swagger:
            summary: Security
            description: Security
            responses:
                200: { description: 'Security information' }

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: ['POST']
    options:
        swagger:
            summary: Login
            description: Login
            responses:
                200: { description: 'Login successful' }
                401: { description: 'Invalid credentials' }

api_update_user:
    path: /api/users/{id}
    controller: App\Controller\UserController::update
    methods: ['POST']
    options:
        swagger:
            summary: Updates a user
            description: Updates a user
            responses:
                200: { description: 'User updated' }
                400: { description: 'Invalid request' }
                404: { description: 'User not found' }

api_get_user_by_id:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUserById
    methods: ['GET']
    options:
        swagger:
            summary: Gets a user by id
            description: Gets a user by id
            responses:
                200: { description: 'User found' }
                404: { description: 'User not found' }

